### ISSUE TITLE
Installation has not been configured error while using this docker image with singularity

### ISSUE THREAD

**Issue by NishiPhalke** [inutano/docker-sra-toolkit#5]
Hi, 

I tried to use your docker image with singularity, but getting below error. Am I missing something?
![image](https://user-images.githubusercontent.com/30417924/140149323-ac621d5c-445f-43f0-84e1-96226fda3f97.png)

**Comment by inutano** [comment]
Yes, it's noted in the README
https://github.com/inutano/docker-sra-toolkit

It's the problem of the latest version of sra toolkit which needs to be configured manually. It makes it difficult to package in fully isolated container. Please consider the official image as described in README
